#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

preflight() {
  if [[ "$OSTYPE" != darwin* ]]; then
    print_error "This installer is macOS-only (detected: $OSTYPE)."
    exit 1
  fi
  if ! command -v brew >/dev/null 2>&1; then
    print_error "Homebrew not found. Install it from https://brew.sh first."
    exit 1
  fi
}

backup_file() {
  local target="$1"
  if [ -e "$target" ] || [ -L "$target" ]; then
    local backup="${target}.bak.$(date +%s)"
    cp -RP "$target" "$backup"
    print_warning "Backed up $target → $backup"
  fi
}

link_file() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
    print_status "$(basename "$dst") already linked"
    return
  fi
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    backup_file "$dst"
    rm -rf "$dst"
  fi
  ln -s "$src" "$dst"
  print_success "Linked $dst → $src"
}

install_zsh_config() {
  print_status "Installing zsh configuration..."
  link_file "$SCRIPT_DIR/zsh/.zshrc" "$HOME/.zshrc"
}

install_aliases() {
  print_status "Installing zsh aliases..."
  link_file "$SCRIPT_DIR/zsh/aliases.sh" "$HOME/.config/zsh/aliases.sh"
}

install_ghostty_config() {
  print_status "Installing Ghostty configuration..."
  link_file "$SCRIPT_DIR/ghostty/config" "$HOME/.config/ghostty/config"
}

install_git_config() {
  print_status "Installing git configuration..."
  link_file "$SCRIPT_DIR/git/config" "$HOME/.config/git/config"
  link_file "$SCRIPT_DIR/git/ignore" "$HOME/.config/git/ignore"

  local id="$HOME/.config/git/identity"
  if [ ! -f "$id" ]; then
    cat > "$id" <<'EOF'
# Default git identity. Generated by install.sh — edit, don't commit.
[user]
	name = TODO Your Name
	email = TODO@example.com
	signingkey = ~/.ssh/id_ed25519.pub

[commit]
	gpgsign = true
[tag]
	gpgsign = true
[gpg]
	format = ssh
[gpg "ssh"]
	allowedSignersFile = ~/.config/git/allowed_signers
EOF
    print_warning "Wrote stub $id — edit with your real name/email before committing"
  fi

  local idp="$HOME/.config/git/identity.personal"
  if [ ! -f "$idp" ]; then
    cat > "$idp" <<'EOF'
# Personal identity override. Loaded for ~/Developer/personal/ and ~/Developer/dotfiles/.
[user]
	email = TODO@example.com
EOF
    print_warning "Wrote stub $idp — edit with your personal email before committing"
  fi
}

install_git_signing() {
  print_status "Configuring git SSH signing..."
  local key="$HOME/.ssh/id_ed25519"
  local pub="$key.pub"
  local signers="$HOME/.config/git/allowed_signers"

  if [ ! -f "$key" ]; then
    print_status "No SSH key found — generating ed25519 (you'll be prompted for a passphrase)"
    mkdir -p "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"
    ssh-keygen -t ed25519 -f "$key"
  fi

  # Resolve the effective default-identity email through git's include chain.
  local email
  email="$(git config --file "$HOME/.config/git/config" --includes --get user.email 2>/dev/null || true)"

  if [ -z "$email" ] || [[ "$email" == TODO* ]]; then
    print_warning "user.email is unset or still a placeholder — skipping allowed_signers."
    print_warning "Edit ~/.config/git/identity, then re-run ./install.sh"
  else
    local desired
    desired="$email $(awk '{print $1, $2}' "$pub")"
    if [ ! -f "$signers" ] || [ "$(cat "$signers")" != "$desired" ]; then
      print_status "Writing $signers"
      printf '%s\n' "$desired" > "$signers"
    fi
    print_success "Git SSH signing configured"
  fi

  print_warning "Upload $pub to GitHub as both an authentication AND signing key:"
  print_warning "  https://github.com/settings/keys"
}

install_docker_plugins() {
  print_status "Installing docker CLI plugins..."
  local prefix
  prefix="$(brew --prefix)"
  link_file "$prefix/opt/docker-compose/bin/docker-compose" "$HOME/.docker/cli-plugins/docker-compose"
  link_file "$prefix/opt/docker-buildx/bin/docker-buildx"   "$HOME/.docker/cli-plugins/docker-buildx"
}

install_fnm_node() {
  if ! command -v fnm >/dev/null 2>&1; then
    print_warning "fnm not found on PATH — skipping Node LTS install"
    return
  fi
  print_status "Installing latest Node.js LTS via fnm..."
  eval "$(fnm env --shell bash)"
  fnm install --lts
  fnm default lts-latest
  print_success "Node $(fnm exec --using=lts-latest -- node --version) set as fnm default"
}

install_oh_my_zsh() {
  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    print_status "Installing Oh My Zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    print_success "Oh My Zsh installed"
  else
    print_status "Oh My Zsh already installed"
  fi
}

brew_sync() {
  local file="$SCRIPT_DIR/homebrew/Brewfile"
  brew bundle install --file "$file"

  if [ "$CLEANUP" -eq 1 ]; then
    print_status "Removing packages no longer in Brewfile..."
    brew bundle cleanup --force --file "$file"
    return
  fi

  local out drift
  out="$(brew bundle cleanup --file "$file" 2>&1)" || true
  # Keep only the "Would uninstall ..." sections; drop brew cache cleanup noise.
  drift="$(echo "$out" | awk '
    /^Would uninstall (formulae|casks|taps):/ { capture=1; print; next }
    /^Would `brew cleanup`/ || /^==>/ { capture=0 }
    capture { print }
  ')"

  if [ -z "$drift" ]; then
    print_status "Brewfile in sync"
  else
    print_warning "Brewfile drift detected:"
    echo "$drift"
    print_warning "Run './install.sh --cleanup' to uninstall these."
  fi
}

install_zsh_plugins() {
  local custom_dir="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins"

  mkdir -p "$custom_dir"

  clone_or_update() {
    local repo="$1"
    local dir="$2"

    if [ ! -d "$dir" ]; then
      print_status "Installing $(basename "$dir")..."
      git clone "$repo" "$dir"
      print_success "$(basename "$dir") installed"
    else
      print_status "Updating $(basename "$dir")..."
      if git -C "$dir" pull --ff-only --quiet; then
        print_success "$(basename "$dir") up to date"
      else
        print_warning "$(basename "$dir") could not fast-forward; leaving as-is"
      fi
    fi
  }

  clone_or_update https://github.com/zsh-users/zsh-autosuggestions "$custom_dir/zsh-autosuggestions"
  clone_or_update https://github.com/zsh-users/zsh-syntax-highlighting "$custom_dir/zsh-syntax-highlighting"
  clone_or_update https://github.com/zsh-users/zsh-completions "$custom_dir/zsh-completions"
}

main() {
  CLEANUP=0
  for arg in "$@"; do
    case "$arg" in
      --cleanup) CLEANUP=1 ;;
      -h|--help)
        echo "Usage: ./install.sh [--cleanup]"
        echo "  --cleanup  Uninstall Homebrew packages no longer in the Brewfile."
        exit 0
        ;;
      *)
        print_error "Unknown argument: $arg"
        exit 1
        ;;
    esac
  done

  print_status "Starting installation..."

  preflight

  brew_sync

  install_docker_plugins
  install_fnm_node
  install_oh_my_zsh
  install_zsh_plugins
  install_zsh_config
  install_aliases
  install_git_config
  install_git_signing
  install_ghostty_config

  print_success "All dotfiles installed successfully!"
  print_warning "Restart your terminal to apply changes."

  if command -v colima >/dev/null 2>&1 && ! colima status >/dev/null 2>&1; then
    print_warning "colima is not running — run 'colima start' to launch the docker runtime"
  fi
}

main "$@"
